#!/usr/bin/env python3
"""
Merge BED regions with columns extracted from processed pileup result files.

Given a BED file and one or more processed result files produced by
`correct_read.py` (or its streaming variant), this script lines up rows by
chromosome plus start coordinate (accounting for the processed file using
1-based starts) and appends the last two columns from each processed file onto
the corresponding BED row. Rows with no matches in a processed file are always
retained and filled with "-1" "-1" for that file so the output row count
matches the BED input.

Example:
    python3 merge_bed_with_processed.py regions.bed processed1.txt processed2.txt -o merged_output.tsv
"""

import argparse
import os
import sys
from collections import defaultdict
from typing import DefaultDict, List, Tuple


def read_bed_rows(bed_path: str) -> List[List[str]]:
    """Return BED rows as lists of fields, skipping empty lines."""
    rows: List[List[str]] = []
    with open(bed_path, "r") as bed_file:
        for line_num, raw_line in enumerate(bed_file, start=1):
            line = raw_line.rstrip("\n")
            if not line:
                continue
            fields = line.split("\t")
            if len(fields) < 3:
                raise ValueError(f"BED line {line_num} in {bed_path} has fewer than 3 columns: {line}")
            rows.append(fields)
    return rows


def build_processed_lookup(processed_path: str) -> DefaultDict[Tuple[str, int], List[Tuple[str, str]]]:
    """Build a lookup from (chrom, start0) to a queue of (col-1, col) values."""
    lookup: DefaultDict[Tuple[str, int], List[Tuple[str, str]]] = defaultdict(list)
    with open(processed_path, "r") as proc_file:
        for line_num, raw_line in enumerate(proc_file, start=1):
            line = raw_line.rstrip("\n")
            if not line:
                continue
            fields = line.split("\t")
            if len(fields) < 2:
                raise ValueError(
                    f"Processed file {processed_path} line {line_num} has fewer than 2 columns: {line}"
                )
            chrom = fields[0]
            try:
                start1 = int(fields[1])
            except ValueError as exc:
                raise ValueError(
                    f"Processed file {processed_path} line {line_num} has non-integer second column: {fields[1]}"
                ) from exc
            start0 = start1 - 1  # processed second column is original start + 1
            value_pair = (fields[-2], fields[-1]) if len(fields) >= 2 else ("-1", "-1")
            lookup[(chrom, start0)].append(value_pair)
    return lookup


def merge_rows(
    bed_rows: List[List[str]],
    processed_columns_per_file: List[List[Tuple[str, str]]],
) -> List[str]:
    """Append processed columns to every BED row, preserving row count."""
    merged_lines: List[str] = []
    num_rows = len(bed_rows)
    for idx in range(num_rows):
        merged_fields = list(bed_rows[idx])
        for proc_columns in processed_columns_per_file:
            c1, c2 = proc_columns[idx]
            merged_fields.extend([c1, c2])
        merged_lines.append("\t".join(merged_fields))
    return merged_lines


def write_output(lines: List[str], output_path: str) -> None:
    """Write merged lines to stdout or a specified file."""
    if output_path == "-":
        for line in lines:
            print(line)
    else:
        with open(output_path, "w") as out_file:
            if lines:
                out_file.write("\n".join(lines))
                out_file.write("\n")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Merge a BED file with the trailing columns from one or more processed result files. "
            "Rows are matched by (chrom, start) with processed starts assumed to be 1-based; "
            "missing matches are filled with -1/-1 so the output row count stays aligned with the BED."
        )
    )
    parser.add_argument("bed_file", help="Path to the BED file containing the original regions.")
    parser.add_argument(
        "processed_files",
        nargs="+",
        help="One or more processed output files generated by correct_read.py.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="-",
        help="Output path (default: stdout).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_arguments()

    bed_rows = read_bed_rows(args.bed_file)
    if not bed_rows:
        write_output([], args.output)
        return

    bed_keys: List[Tuple[str, int]] = []
    for row in bed_rows:
        try:
            start0 = int(row[1])
        except ValueError as exc:
            raise ValueError(f"BED start position is not an integer: {row[1]}") from exc
        bed_keys.append((row[0], start0))

    processed_columns_per_file: List[List[Tuple[str, str]]] = []

    for processed_path in args.processed_files:
        if not os.path.exists(processed_path):
            raise FileNotFoundError(f"Processed file not found: {processed_path}")

        lookup = build_processed_lookup(processed_path)
        columns_for_rows: List[Tuple[str, str]] = []

        for chrom, start0 in bed_keys:
            key = (chrom, start0)
            queue = lookup.get(key)
            if queue:
                columns_for_rows.append(queue.pop(0))
                if not queue:
                    del lookup[key]
            else:
                columns_for_rows.append(("-1", "-1"))

        leftover = sum(len(v) for v in lookup.values())
        if leftover:
            print(
                f"Warning: {processed_path} has {leftover} rows that did not match the BED entries.",
                file=sys.stderr,
            )

        processed_columns_per_file.append(columns_for_rows)

    merged_lines = merge_rows(bed_rows, processed_columns_per_file)
    write_output(merged_lines, args.output)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)
